package com.kompas.model.kompas.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Created by White Stream on 11.02.2017.
 */
@AllArgsConstructor
@Getter
public enum DrawingObjectType {
    ALL_OBJ(0, ""),
    LINESEG_OBJ(1, "отрезок"),
    CIRCLE_OBJ(2, "окружность"),
    ARC_OBJ(3, "дуга окружности"),
    TEXT_OBJ(4, "текст"),
    POINT_OBJ(5, "точка"),
    HATCH_OBJ(7, "штриховка"),
    BEZIER_OBJ(8, "кривая Безье"),
    LDIMENSION_OBJ(9, "линейный размер"),
    ADIMENSION_OBJ(10, "угловой размер"),
    DDIMENSION_OBJ(13, "диаметральный размер"),
    RDIMENSION_OBJ(14, "радиальный размер"),
    RBREAKDIMENSION_OBJ(15, "радиальный размер с изломом"),
    ROUGH_OBJ(16, "обозначение шероховатости"),
    BASE_OBJ(17, "обозначение базы"),
    WPOINTER_OBJ(18, "стрелка направления взгляда"),
    CUT_OBJ(19, "линия разреза"),
    LEADER_OBJ(20, "линия-выноска"),
    POSLEADER_OBJ(21, "позиционная линия-выноска"),
    BRANDLEADER_OBJ(22, "линия-выноска для обозначения клеймения"),
    MARKERLEADER_OBJ(23, "линия-выноска для обозначения маркирования"),
    TOLERANCE_OBJ(24, "обозначение допуска формы"),
    TABLE_OBJ(25, "таблица в графическом документе"),
    CONTOUR_OBJ(26, "контур"),
    MACRO_OBJ(27, "нетипизированный макроэлемент"),
    LINE_OBJ(28, "прямая"),
    LAYER_OBJ(29, "слой"),
    FRAGMENT_OBJ(30, "вставленный фрагмент"),
    POLYLINE_OBJ(31, "ломаная линия"),
    ELLIPSE_OBJ(32, "эллипс"),
    NURBS_OBJ(33, "кривая NURBS"),
    ELLIPSE_ARC_OBJ(34, "дуга эллипса"),
    RECTANGLE_OBJ(35, "прямоугольник"),
    REGULARPOLYGON_OBJ(36, "правильный многоугольник"),
    EQUID_OBJ(37, "эквидистанта"),
    LBREAKDIMENSION_OBJ(38, "линейный размер с обрывом"),
    ABREAKDIMENSION_OBJ(39, "Угловой размер с обрывом"),
    ORDINATEDIMENSION_OBJ(40, "Размер высоты"),
    COLORFILL_OBJ(41, "Фоновая заливка цветом"),
    CENTREMARKER_OBJ(42, "Обозначение центра"),
    ARCDIMENSION_OBJ(43, "Размер длины дуги"),
    SPC_OBJ(44, "объект спецификации"),
    RASTER_OBJ(45, "Растровый объект"),
    CHANGE_LEADER_OBJ(46, "Обозначение изменения"),
    REMOTE_ELEMENT_OBJ(47, "Выносной элемент"),
    AXISLINE_OBJ(48, "Осевая линия"),
    OLEOBJECT_OBJ(49, "Вставка OLE объекта"),
    KNOTNUMBER_OBJ(50, "Объект номер узла"),
    BRACE_OBJ(51, "Объект фигурная скобка"),
    POSNUM_OBJ(52, "Объект обозначение позиции"),
    MARKONLDR_OBJ(53, "Объект обозначение позиции"),
    MARKWOLDR_OBJ(54, "Объект обозначение позиции"),
    WAVELINE_OBJ(55, "Объект волнистая линия"),
    DIRAXIS_OBJ(56, "Объект прямая ось"),
    BROKENLINE_OBJ(57, "Линия обрыва с изломами"),
    CIRCLEAXIS_OBJ(58, "Круговая ось"),
    ARCAXIS_OBJ(59, "Дуговая ось"),
    CUTUNITMARKING(60, "Обозначение узла в сечении"),
    UNITMARKING(61, "Обозначение узла"),
    MULTITEXTLEADER(62, "Выносная надпись к многослойным конструкциям"),
    EXTERNALVIEW_OBJ(63, "Вставка внешнего вида"),
    MULTILINE_OBJ(72, "Мультилиния"),
    BUILDINGCUTLINE_OBJ(73, "Линия разреза для СПДС"),
    SPECIFICATION_OBJ(121, "спецификация на листе"),
    SPECROUGH_OBJ(122, "обозначение неуказанной шероховатости"),
    VIEW_OBJ(123, "Вид"),
    DOCUMENT_OBJ(124, "графический документ (чертеж или фрагмент)"),
    TECHNICALDEMAND_OBJ(125, "технические требования"),
    STAMP_OBJ(126, "основная надпись"),
    SELECT_GROUP_OBJ(127, "группа выбора"),
    NAME_GROUP_OBJ(128, "именованная группа"),
    WORK_GROUP_OBJ(129, "рабочая группа"),
    SPC_DOCUMENT_OBJ(130, "документ-спецификация"),
    D3_DOCUMENT_OBJ(131, "документ-модель (деталь или сборка)"),
    CHANGE_LIST_OBJ(132, "таблица изменений"),
    TXT_DOCUMENT_OBJ(133, "текстовый документ"),
    ALL_DOCUMENTS(134, "все документы");

    private int index;
    private String name;
}
